import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, Section } from '@/components/ui/card';
import { Input, Label, Select, Textarea } from '@/components/ui/field';
import { formatDate } from '@/lib/format';
import { TEMPLATES, TEMPLATE_NAMES, type SequenceTemplate } from '@/lib/sequences/templates';
import {
  assignSequence,
  markSequenceEmailSent,
  pauseSequence,
  resumeSequence,
  skipSequenceEmail,
} from '@/app/companies/[id]/sequence-actions';

type SequenceEmail = {
  id: string;
  step_number: number;
  subject: string | null;
  body: string | null;
  status: 'draft' | 'approved' | 'sent' | 'skipped';
  scheduled_date: string | null;
  sent_date: string | null;
};

type Sequence = {
  id: string;
  template_name: string;
  current_step: number;
  next_send_date: string | null;
  status: 'active' | 'paused' | 'completed';
  deal: { id: string; deal_name: string } | null;
  emails: SequenceEmail[];
};

export function SequencesSection({
  companyId,
  sequences,
  deals,
}: {
  companyId: string;
  sequences: Sequence[];
  deals: { id: string; deal_name: string }[];
}) {
  const assignAction = assignSequence.bind(null, companyId);

  return (
    <Section
      title={`Sequences (${sequences.length})`}
      action={
        <details className="relative">
          <summary className="cursor-pointer text-xs text-accent hover:underline">+ Assign sequence</summary>
          <form action={assignAction} className="absolute right-0 z-10 mt-2 w-80 space-y-2 rounded border border-border bg-white p-3 shadow-md">
            <div className="space-y-1">
              <Label htmlFor="seq-deal">Deal</Label>
              <Select id="seq-deal" name="deal_id" defaultValue={deals[0]?.id ?? ''} required>
                {deals.length === 0 && <option value="">No deals — create one first</option>}
                {deals.map((d) => (
                  <option key={d.id} value={d.id}>{d.deal_name}</option>
                ))}
              </Select>
            </div>
            <div className="space-y-1">
              <Label htmlFor="seq-template">Template</Label>
              <Select id="seq-template" name="template_name" defaultValue="cold_outreach" required>
                {TEMPLATE_NAMES.map((name) => (
                  <option key={name} value={name}>{TEMPLATES[name].label}</option>
                ))}
              </Select>
            </div>
            <p className="text-xs text-muted">
              The first draft is generated immediately. Later drafts get auto-generated by the daily cron, ~2 days before they&rsquo;re due.
            </p>
            <Button type="submit" className="w-full" disabled={deals.length === 0}>
              Assign
            </Button>
          </form>
        </details>
      }
    >
      {sequences.length === 0 ? (
        <Card className="px-3 py-2.5">
          <p className="text-sm text-muted">No sequences assigned yet.</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {sequences.map((seq) => (
            <SequenceCard key={seq.id} companyId={companyId} sequence={seq} />
          ))}
        </div>
      )}
    </Section>
  );
}

function SequenceCard({ companyId, sequence }: { companyId: string; sequence: Sequence }) {
  const template = TEMPLATES[sequence.template_name];
  const totalSteps = template?.steps.length ?? 0;

  return (
    <Card className="overflow-hidden">
      <div className="flex items-baseline justify-between gap-3 border-b border-border bg-bg px-3 py-2">
        <div>
          <div className="flex items-baseline gap-2">
            <span className="text-sm font-medium">{template?.label ?? sequence.template_name}</span>
            <Badge
              variant={
                sequence.status === 'completed'
                  ? 'won'
                  : sequence.status === 'paused'
                  ? 'muted'
                  : 'accent'
              }
            >
              {sequence.status}
            </Badge>
            <span className="text-xs text-muted">
              step {sequence.current_step + 1} of {totalSteps}
            </span>
          </div>
          <p className="mt-0.5 text-xs text-muted">
            {sequence.deal?.deal_name ?? 'deal removed'}
            {sequence.next_send_date && sequence.status === 'active' && (
              <> · next draft on {formatDate(sequence.next_send_date)}</>
            )}
          </p>
        </div>
        <div className="flex gap-2">
          {sequence.status === 'active' && (
            <form action={pauseSequence.bind(null, companyId, sequence.id)}>
              <Button type="submit" variant="ghost" className="text-xs">Pause</Button>
            </form>
          )}
          {sequence.status === 'paused' && (
            <form action={resumeSequence.bind(null, companyId, sequence.id)}>
              <Button type="submit" variant="ghost" className="text-xs">Resume</Button>
            </form>
          )}
        </div>
      </div>

      <ul>
        {sequence.emails.map((email) => (
          <SequenceEmailRow key={email.id} companyId={companyId} email={email} />
        ))}
      </ul>
    </Card>
  );
}

function SequenceEmailRow({ companyId, email }: { companyId: string; email: SequenceEmail }) {
  const isReady = email.status === 'draft' && !!email.body;
  const isPending = email.status === 'draft' && !email.body;
  const sentAction = markSequenceEmailSent.bind(null, companyId, email.id);
  const skipAction = skipSequenceEmail.bind(null, companyId, email.id);

  return (
    <li className="border-b border-border px-3 py-2.5 last:border-b-0">
      <div className="flex items-baseline justify-between gap-3">
        <div className="flex items-baseline gap-2 text-xs text-muted">
          <span className="font-mono">step {email.step_number + 1}</span>
          {email.scheduled_date && (
            <span>· scheduled {formatDate(email.scheduled_date)}</span>
          )}
          {email.sent_date && <span>· sent {formatDate(email.sent_date)}</span>}
        </div>
        <StatusBadge status={email.status} ready={isReady} pending={isPending} />
      </div>

      {email.subject && <p className="mt-1 text-sm font-medium">{email.subject}</p>}

      {isReady && (
        <details className="mt-2">
          <summary className="cursor-pointer text-xs text-accent hover:underline">
            Review &amp; mark sent
          </summary>
          <form action={sentAction} className="mt-2 space-y-2">
            <div className="space-y-1">
              <Label htmlFor={`subject-${email.id}`}>Subject</Label>
              <Input id={`subject-${email.id}`} name="subject" defaultValue={email.subject ?? ''} required />
            </div>
            <div className="space-y-1">
              <Label htmlFor={`body-${email.id}`}>Body</Label>
              <Textarea
                id={`body-${email.id}`}
                name="body"
                defaultValue={email.body ?? ''}
                className="min-h-[180px] font-mono text-[13px]"
                required
              />
            </div>
            <div className="flex gap-2">
              <Button type="submit">Mark as sent</Button>
              <Button
                type="submit"
                variant="secondary"
                formAction={skipAction.bind(null)}
              >
                Skip
              </Button>
            </div>
          </form>
        </details>
      )}

      {isPending && (
        <p className="mt-1 text-xs text-muted">
          Awaiting auto-draft — will appear ~2 days before scheduled date, or you can force it via the sequences cron.
        </p>
      )}

      {email.status === 'sent' && email.body && (
        <details className="mt-1 text-xs">
          <summary className="cursor-pointer text-muted hover:text-ink">View sent body</summary>
          <pre className="mt-2 whitespace-pre-wrap rounded bg-bg p-2 font-mono text-[12px]">{email.body}</pre>
        </details>
      )}
    </li>
  );
}

function StatusBadge({
  status,
  ready,
  pending,
}: {
  status: SequenceEmail['status'];
  ready: boolean;
  pending: boolean;
}) {
  if (ready) return <Badge variant="due">draft ready</Badge>;
  if (pending) return <Badge variant="muted">awaiting draft</Badge>;
  if (status === 'sent') return <Badge variant="won">sent</Badge>;
  if (status === 'skipped') return <Badge variant="muted">skipped</Badge>;
  return <Badge variant="default">{status}</Badge>;
}
